# Production Docker Compose - Uses Pre-built Images from Docker Hub
# Copyright (C) 2025 Kasa Monitor Contributors
# Licensed under GPL v3

version: '3.8'

services:
  kasa-monitor:
    image: xante8088/kasa-monitor:pi5  # Replace xante8088 with your Docker Hub username
    container_name: kasa-monitor
    restart: unless-stopped
    ports:
      - "3000:3000"   # Frontend
      - "8000:8000"   # Backend API
    volumes:
      # Persist database and logs
      - kasa_data:/app/data
      - kasa_logs:/app/logs
      # Optional: Custom SSL certificates (uncomment if needed)
      # - kasa_ssl:/app/ssl:ro
    environment:
      # Database configuration
      - SQLITE_PATH=/app/data/kasa_monitor.db
      
      # Optional: InfluxDB configuration
      # - INFLUXDB_URL=http://influxdb:8086
      # - INFLUXDB_TOKEN=your-token-here
      # - INFLUXDB_ORG=kasa-monitor
      # - INFLUXDB_BUCKET=device-data
      
      # Optional: TP-Link Cloud credentials for device discovery
      # - TPLINK_USERNAME=user@example.com
      # - TPLINK_PASSWORD=your-password
      
      # JWT Secret (will auto-generate if not provided)
      # - JWT_SECRET_KEY=your-secret-key-here
      
      # Network security settings
      - ALLOW_LOCAL_ONLY=true
      - ALLOWED_NETWORKS=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
      
      # Performance tuning for Raspberry Pi
      - NODE_OPTIONS=--max-old-space-size=1024
      - PYTHONUNBUFFERED=1
    
    networks:
      - kasa-network
    
    # Resource limits optimized for Raspberry Pi 5
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/devices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: InfluxDB for advanced time-series data
  influxdb:
    image: influxdb:2.7-alpine
    container_name: kasa-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=kasaMonitor2025
      - DOCKER_INFLUXDB_INIT_ORG=kasa-monitor
      - DOCKER_INFLUXDB_INIT_BUCKET=device-data
    networks:
      - kasa-network
    profiles:
      - influxdb
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

networks:
  kasa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  # Kasa Monitor data volumes
  kasa_data:
    driver: local
  kasa_logs:
    driver: local
  kasa_ssl:
    driver: local
  # InfluxDB volumes
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local