[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
known_first_party = ["auth", "database", "models", "cache_manager", "data_aggregation", "data_export", "hook_system", "plugin_system"]