name: Docker Build (Manual)

# This workflow is for manual builds only
# Use the main docker-build.yml for automatic builds on code changes

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
      platforms:
        description: 'Target platforms (comma-separated)'
        required: false
        default: 'linux/amd64,linux/arm64'
      reason:
        description: 'Reason for manual build'
        required: true
        default: 'Manual build requested'

env:
  REGISTRY: docker.io
  IMAGE_NAME: kasa-monitor

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Verify secrets are set
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ ERROR: DOCKER_USERNAME secret is not set!"
          echo "Go to Settings → Secrets and variables → Actions"
          echo "Add a secret named DOCKER_USERNAME with your Docker Hub username"
          exit 1
        fi
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ ERROR: DOCKER_PASSWORD secret is not set!"
          echo "Go to Settings → Secrets and variables → Actions"
          echo "Add a secret named DOCKER_PASSWORD with your Docker Hub access token"
          exit 1
        fi
        echo "✅ Docker Hub secrets are configured"
        echo "Username starts with: $(echo '${{ secrets.DOCKER_USERNAME }}' | cut -c1-3)***"
        echo "Username length: $(echo -n '${{ secrets.DOCKER_USERNAME }}' | wc -c) characters"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ github.event.inputs.tag || 'latest' }}
          type=raw,value=pi5,enable=${{ github.event.inputs.tag == 'latest' || github.event.inputs.tag == '' }}
          type=sha,prefix=manual-
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
        labels: |
          org.opencontainers.image.title=Kasa Monitor
          org.opencontainers.image.description=Web application for monitoring Kasa smart devices - Raspberry Pi optimized
          org.opencontainers.image.vendor=Kasa Monitor Contributors
          org.opencontainers.image.licenses=GPL-3.0
          org.opencontainers.image.source.trigger=manual
          org.opencontainers.image.build.reason=${{ github.event.inputs.reason }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_DATE=${{ steps.meta.outputs.created }}
          BUILD_VERSION=${{ github.event.inputs.tag || 'latest' }}
        
    - name: Summary
      if: success()
      run: |
        echo "## ✅ Docker Build Successful!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Build Information:" >> $GITHUB_STEP_SUMMARY
        echo "- **Trigger**: Manual" >> $GITHUB_STEP_SUMMARY
        echo "- **Reason**: ${{ github.event.inputs.reason }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag**: ${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by**: @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Images pushed to Docker Hub:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Pull command:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
        echo "docker pull ${{ secrets.DOCKER_USERNAME }}/kasa-monitor:${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY