name: Docker Build Check (PR)

# This workflow validates Docker builds on pull requests  
# It builds but does NOT push images - only validates build process

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      # Docker configuration
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
      - '.dockerignore'
      
      # Backend source code
      - 'backend/**/*.py'
      - 'requirements.txt'
      
      # Frontend source code
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - 'src/**/*.js'
      - 'src/**/*.jsx'
      - 'src/**/*.css'
      - 'public/**'
      
      # Build configuration
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.js'
      - 'tsconfig.json'
      
      # Workflow configuration
      - '.github/workflows/docker-build-pr.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: ${{ matrix.platform }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/test/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=pr
          type=raw,value=pr-${{ github.event.pull_request.number }}
    
    - name: Build Docker image (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ matrix.platform }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Summary
      if: success()
      run: |
        echo "## ✅ Docker Build Test Successful!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Build Information:" >> $GITHUB_STEP_SUMMARY
        echo "- **PR**: #${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform**: ${{ matrix.platform }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Author**: @${{ github.event.pull_request.user.login }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ This PR's changes build successfully for ${{ matrix.platform }}" >> $GITHUB_STEP_SUMMARY
    
    - name: Comment on PR
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Docker build failed for platform: ${{ matrix.platform }}\n\nPlease check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
          })