name: Manual Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag for Docker image'
        required: true
        default: 'v1.2.0'
      push_to_registry:
        description: 'Push to Docker registry'
        required: true
        default: true
        type: boolean

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: xante8088/kasa-monitor

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: ${{ inputs.push_to_registry }}
      uses: docker/login-action@v3
      continue-on-error: true
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ inputs.version_tag }}
          type=sha,prefix={{branch}}-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push_to_registry }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Print image info
      run: |
        echo "🐳 Docker image built successfully!"
        echo "📦 Tags: ${{ steps.meta.outputs.tags }}"
        if [ "${{ inputs.push_to_registry }}" = "true" ]; then
          echo "✅ Image pushed to registry"
        else
          echo "📋 Image built locally only"
        fi